GET http://localhost:3000/institute/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlN0YW5mb3JkIiwidGVhY2hlcnMiOltdLCJzdHVkZW50cyI6W10sImNvdXJzZXMiOltdLCJpYXQiOjE2MTkwODY1MTJ9.3vjH8GZSeNkoThJ0esCPbsf3owwTAu2FmXXAwJJQ1qI

###########

POST http://localhost:3000/institute/
Content-Type: application/json

{
    "name":"Stanford",
    "password":"password"
}

#########

POST http://localhost:3000/institute/login
Content-Type: application/json

{
    "name":"Stanford",
    "password":"password"
}

#########

POST http://localhost:3000/institute/add-student
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlN0YW5mb3JkIiwidGVhY2hlcnMiOltdLCJzdHVkZW50cyI6W10sImNvdXJzZXMiOltdLCJpYXQiOjE2MTkwODY1MTJ9.3vjH8GZSeNkoThJ0esCPbsf3owwTAu2FmXXAwJJQ1qI
Content-Type: application/json

{
    "email":"saratangajala@gmail.com"
}

###########

POST http://localhost:3000/institute/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlN0YW5mb3JkIiwidGVhY2hlcnMiOltdLCJzdHVkZW50cyI6W10sImNvdXJzZXMiOltdLCJpYXQiOjE2MTkwODY1MTJ9.3vjH8GZSeNkoThJ0esCPbsf3owwTAu2FmXXAwJJQ1qI


###########
GET http://localhost:3000/institute/students
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlN0YW5mb3JkIiwidGVhY2hlcnMiOltdLCJzdHVkZW50cyI6W10sImNvdXJzZXMiOltdLCJpYXQiOjE2MTkwODY1MTJ9.3vjH8GZSeNkoThJ0esCPbsf3owwTAu2FmXXAwJJQ1qI